language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO=1.4.5
  - DJANGO=1.3.7
  - DJANGO=1.5
  - DJANGO=1.6.1
  - DJANGO=1.7
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.6.1
    - python: "2.6"
      env: DJANGO=1.7
  include:
    - python: "3.2"
      env: DJANGO=1.5
    - python: "3.3"
      env: DJANGO=1.5
    - python: "3.2"
      env: DJANGO=1.6.1
    - python: "3.3"
      env: DJANGO=1.6.1
    - python: "3.2"
      env: DJANGO=1.7
    - python: "3.3"
      env: DJANGO=1.7
    - python: "3.4"
      env: DJANGO=1.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py -q install
script:
  - python setup.py test

